# Generated by Django 3.2.8 on 2021-12-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='city',
            field=models.CharField(max_length=256, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.CharField(max_length=256, verbose_name='user'),
        ),
    ]
