# Generated by Django 3.2.8 on 2021-12-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211202_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='city',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='address',
            field=models.CharField(default=None, max_length=256, verbose_name='address'),
            preserve_default=False,
        ),
    ]
