# Generated by Django 3.2.8 on 2022-02-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=256, verbose_name='city')),
                ('state', models.CharField(max_length=256, verbose_name='state')),
                ('rating', models.IntegerField()),
                ('text', models.CharField(max_length=256, verbose_name='text')),
            ],
        ),
    ]
