# Generated by Django 3.2.8 on 2022-02-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('state', models.CharField(max_length=16, verbose_name='state')),
                ('safelivingscore', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='safelivingscore')),
                ('crimescore', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='crimescore')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='longitude')),
                ('population', models.IntegerField(verbose_name='population')),
                ('propertycrimescore', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='propertycrimescore')),
                ('violentcrimescore', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='violentcrimescore')),
            ],
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'state'), name='City State Name Unique'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
