# Generated by Django 3.2.8 on 2022-02-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citybase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='crimescore',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='crimescore'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='population'),
        ),
        migrations.AlterField(
            model_name='city',
            name='propertycrimescore',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='propertycrimescore'),
        ),
        migrations.AlterField(
            model_name='city',
            name='safelivingscore',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='safelivingscore'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='city',
            name='violentcrimescore',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='violentcrimescore'),
        ),
    ]
